-- ============================================================================
-- Compassion Market — skema database (Supabase / Postgres)
-- Jalankan berurutan: 01_schema -> 02_logic -> 03_security -> 04_seed
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Profil karyawan & admin.
-- Karyawan TIDAK punya akun auth.users: profil dibuat admin (menu Pengguna) dan
-- dipilih sendiri lewat halaman "Masuk sebagai" tanpa password (self service
-- pilih identitas, verifikasi barang tetap lewat admin sebelum tayang).
-- Admin tetap wajib akun Supabase Auth asli (email + password) -> has_login = true.
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  email text,
  name text not null default '',
  emp_id text,
  phone text,
  department text,
  role text not null default 'employee' check (role in ('employee', 'admin')),
  has_login boolean not null default false,   -- true = akun asli Supabase Auth (wajib untuk admin)
  bank_name text,
  bank_account text,
  bank_holder text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
-- Cegah email dobel (dipakai juga untuk pencarian identitas via email penuh)
create unique index if not exists profiles_email_unique_idx on public.profiles (lower(email)) where email is not null;

-- ---------------------------------------------------------------------------
-- Master data & konfigurasi (semua dikelola admin dari halaman Admin)
-- ---------------------------------------------------------------------------
create table if not exists public.settings (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text default '🏷️',
  zone text,                          -- area di toko 3D (bar_counter, table_center, rack_left, ...)
  size_options text default '',       -- pilihan ukuran dipisah koma, kosong = isian bebas
  active boolean not null default true,
  sort int not null default 0
);

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('qris', 'bank')),
  name text not null,
  bank_name text,
  account_no text,
  account_holder text,
  logo_url text,
  qris_image text,                    -- path di bucket site-assets atau URL penuh
  instructions text,
  active boolean not null default true,
  sort int not null default 0
);

-- ---------------------------------------------------------------------------
-- Barang
-- ---------------------------------------------------------------------------
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  form_no int not null,               -- nomor form -> kode barang CM-<form_no>-<urutan>
  seller_id uuid references public.profiles(id),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text unique,
  submission_id bigint references public.submissions(id),
  seller_id uuid references public.profiles(id),   -- null utk barang titipan/impor manual
  seller_name text,
  category_id bigint references public.categories(id),
  name text not null,
  size text,
  item_condition text check (item_condition in ('baru', 'preloved')),
  condition_pct int check (condition_pct between 0 and 100),
  original_price bigint check (original_price >= 0),  -- harga coret (opsional)
  price bigint not null default 0 check (price >= 0),
  donation_amount bigint not null default 0 check (donation_amount >= 0),  -- nominal donasi acara
  stock int not null default 1 check (stock >= 0),
  summary text,
  condition_note text,
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected', 'hidden')),
  reject_reason text,
  featured boolean not null default false,
  sort_order int not null default 0,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists products_status_idx on public.products(status);
create index if not exists products_seller_idx on public.products(seller_id);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  path text not null,                 -- path di bucket product-photos, atau URL penuh
  sort int not null default 0
);
create index if not exists product_images_product_idx on public.product_images(product_id);

-- ---------------------------------------------------------------------------
-- Flash sale
-- ---------------------------------------------------------------------------
create table if not exists public.flash_sales (
  id bigint generated by default as identity primary key,
  name text not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (end_at > start_at)
);

create table if not exists public.flash_sale_items (
  id bigint generated by default as identity primary key,
  flash_sale_id bigint not null references public.flash_sales(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  flash_price bigint not null check (flash_price >= 0),
  quota int check (quota is null or quota >= 0),
  sold int not null default 0,
  unique (flash_sale_id, product_id)
);

-- ---------------------------------------------------------------------------
-- Kartu stok (mirip stock ledger di ERP): setiap perubahan stok tercatat otomatis
-- ---------------------------------------------------------------------------
create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  qty_change int not null,
  balance int not null,
  type text not null,                 -- initial | adjust | sale | release
  ref text,
  note text,
  user_id uuid,
  created_at timestamptz not null default now()
);
create index if not exists stock_movements_product_idx on public.stock_movements(product_id);

-- ---------------------------------------------------------------------------
-- Pesanan
-- ---------------------------------------------------------------------------
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  code text not null unique,
  buyer_id uuid not null references public.profiles(id),
  buyer_name text,
  status text not null default 'waiting_payment' check (status in
    ('waiting_payment', 'waiting_verification', 'paid', 'ready_pickup', 'completed', 'cancelled', 'expired')),
  payment_method_id bigint references public.payment_methods(id),
  payment_snapshot jsonb,             -- salinan info rekening/QRIS saat order dibuat
  subtotal bigint not null,
  admin_fee bigint not null default 0,
  unique_code int not null default 0,
  total bigint not null,
  proof_path text,                    -- path di bucket payment-proofs
  buyer_note text,
  admin_note text,
  expires_at timestamptz,
  paid_at timestamptz,
  completed_at timestamptz,
  stock_released boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_buyer_idx on public.orders(buyer_id);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  seller_id uuid references public.profiles(id),
  seller_name text,
  code text,
  name text not null,
  price bigint not null,
  normal_price bigint not null,
  qty int not null check (qty > 0),
  flash_item_id bigint references public.flash_sale_items(id),
  payout_status text not null default 'unpaid' check (payout_status in ('unpaid', 'paid')),
  payout_amount bigint,
  payout_at timestamptz,
  payout_ref text
);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_seller_idx on public.order_items(seller_id);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid,
  action text not null,
  entity text,
  entity_id bigint,
  detail jsonb,
  created_at timestamptz not null default now()
);
