-- ============================================================================
-- Compassion Market -- import daftar karyawan Interport (Data User.xlsx)
-- Aman dijalankan ulang: email duplikat (case-insensitive) tidak akan dobel.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- PERBAIKAN SKEMA (jaga-jaga): CREATE TABLE IF NOT EXISTS di migrasi pertama
-- tidak pernah mengubah tabel `profiles` yang sudah ada, jadi perubahan skema
-- untuk fitur "tanpa login karyawan" mungkin belum benar-benar diterapkan.
-- Baris di bawah ini aman dijalankan berkali-kali (idempotent).
-- ---------------------------------------------------------------------------
alter table public.profiles drop constraint if exists profiles_id_fkey;
alter table public.profiles alter column id set default gen_random_uuid();
alter table public.profiles add column if not exists has_login boolean not null default false;
-- Tandai profil yang memang punya akun Supabase Auth asli (kalau sudah ada admin)
update public.profiles p set has_login = true where exists (select 1 from auth.users u where u.id = p.id) and not p.has_login;

-- Cegah email dobel (dipakai juga untuk pencarian identitas via email)
create unique index if not exists profiles_email_unique_idx on public.profiles (lower(email)) where email is not null;

insert into public.profiles (name, email) values
  ('Abdul Rajak', 'Abdul.Rajak@interport.co.id'),
  ('Abdul Zulkifli Perangin Angin', 'abdul.angin@interport.co.id'),
  ('Abraham Kaawoan', 'abraham.kaaowan@interport.co.id'),
  ('Acep Nunuh Nugraha', 'acep.nugraha@interport.co.id'),
  ('Achmad Zaidan', 'achmad.zaidan@interport.co.id'),
  ('Adhitya Syafta', 'adhitya.syafta@interport.co.id'),
  ('Adi Darma Shima', 'adi.shima@interport.co.id'),
  ('Adi Umardani', 'adi.umardani@interport.co.id'),
  ('Adinda Fadia Adila Ali Samad', 'Adinda.Samad@interport.co.id'),
  ('Adinda Sharfina Rakhmania', 'Adinda.Rakhmania@interport.co.id'),
  ('Aditia Rahman Wirawan Wahyono', 'Aditia.Wahyono-INT@interport.co.id'),
  ('Aditya Widyo Nugroho', 'Aditya.Nugroho@interport.co.id'),
  ('Agus Felik Habibi', 'Agus.Habibi@interport.co.id'),
  ('Agus Ramadhany', 'Agus.Ramadhany@interport.co.id'),
  ('Agustian Gozali', 'agustian.gozali@interport.co.id'),
  ('Ahyadil Junianto', 'ahyadil.junianto@interport.co.id'),
  ('Aji Darmadi', 'Aji.Darmadi@interport.co.id'),
  ('Akmaluddin', 'Akmaluddin.A@interport.co.id'),
  ('Aldin Mahendra', 'Aldin.Mahendra@interport.co.id'),
  ('Aliya Nadira Gunawan', 'Aliya.Gunawan@interport.co.id'),
  ('Aloisius Annom Sanjaya', 'AloisiusAnnom.Sanjaya@interport.co.id'),
  ('Aloysius Hartanto', 'Aloysius.Hartanto@interport.co.id'),
  ('Alwin', 'alwin@interport.co.id'),
  ('Alya Dhiya Fauzan', 'alya.fauzan@interport.co.id'),
  ('Alyssa Zahra', 'Alyssa.Zahra@interport.co.id'),
  ('Amransyah', 'Amransyah.A@interport.co.id'),
  ('Andre Adjani Casal', 'andre.casal@interport.co.id'),
  ('Anggita Putri', 'Anggita.Putri@interport.co.id'),
  ('Annas Aditya Farizqi', 'Annas.Farizqi@interport.co.id'),
  ('Annisa Maulydia', 'annisa.maulydia@interport.co.id'),
  ('Anton Padang T', 'Anton.Padang@interport.co.id'),
  ('Ardiman', 'Ardiman.A@interport.co.id'),
  ('Arief Rachmat Fatharoni', 'arief.fatharoni@interport.co.id'),
  ('Arifin', 'Arifin@interport.co.id'),
  ('Aris Wibowo', 'Aris.Wibowo@interport.co.id'),
  ('Arita Voridianto', 'arita.voridianto@interport.co.id'),
  ('Armitha Khanza Leany', 'Armitha.Leany@interport.co.id'),
  ('Arzaly Nugraha', 'Arzaly.Nugraha@interport.co.id'),
  ('Asnawi', 'Asnawi@interport.co.id'),
  ('Astrid Aqiilah Febriana', 'astrid.febriana@interport.co.id'),
  ('Azizi Syaldira Vitricia', 'Azizi.Vitricia@interport.co.id'),
  ('Bahtaria Rohmah', 'Bahtaria.Rohmah@interport.co.id'),
  ('Bambang Widiyono', 'bambang.widiyono@interport.co.id'),
  ('Banu Windyasmoro', 'Banu.Windyasmoro@interport.co.id'),
  ('Basuki Wibawa', 'Basuki.Wibawa@interport.co.id'),
  ('Bernard Giang Tangirerung', 'bernard.giang@interport.co.id'),
  ('Budi Priyanto', 'Budi.Priyanto@interport.co.id'),
  ('Candra Harianto', 'Candra.Harianto@interport.co.id'),
  ('Christoforus Steven Dwinovandi', 'christoforus.dwinovandi@interport.co.id'),
  ('Daffa Al Faros', 'Daffa.Faros@interport.co.id'),
  ('Daffa Indrasta Rasendrya', 'Daffa.Rasendrya@interport.co.id'),
  ('Dayan Naibaho', 'Dayan.Naibaho@interport.co.id'),
  ('Dea Adityo Trimukti', 'dea.trimukti@interport.co.id'),
  ('Debora', 'Debora@interport.co.id'),
  ('Denda Muaziz', 'Denda.Muaziz@interport.co.id'),
  ('Deny Setiawan', 'deny.setiawan@interport.co.id'),
  ('Dhedy Hamriadi Haruna', 'Dhedy.Haruna@interport.co.id'),
  ('Dhia Fadilatul Hasanah', 'Dhia.Hasanah@interport.co.id'),
  ('Dian Mei Fallahati', 'Dian.Fallahati@interport.co.id'),
  ('Dies Harmin Fisie', 'dies.fisie@interport.co.id'),
  ('Diki Pratama Putra', 'Diki.Putra@interport.co.id'),
  ('Dimas Ageng Kurniawan', 'dimas.kurniawan@interport.co.id'),
  ('Dimas Cahyo Wihatmoko', 'Dimas.Wihatmoko@interport.co.id'),
  ('Dinda Maharani', 'Dinda.Maharani@interport.co.id'),
  ('Dody Indra Wisnu', 'dody.wisnu@interport.co.id'),
  ('Donny Rizky Noviar', 'donny.noviar@interport.co.id'),
  ('Eddy Suriyanto', 'eddy.suriyanto@interport.co.id'),
  ('Edelis Dayhyza Maienjel Ginting', 'Edelis.Ginting@interport.co.id'),
  ('Edna Sestina Homer', 'edna.homer@interport.co.id'),
  ('Eko Santoso', 'eko.santoso@interport.co.id'),
  ('Engelika Panggabean', 'Engelika.Panggabean@interport.co.id'),
  ('Eric Hartanuh', 'eric.hartanuh@interport.co.id'),
  ('Faizal Arief Pratama', 'faizal.pratama@interport.co.id'),
  ('Fandy Mahatma Jaya', 'Fandy.Jaya@interport.co.id'),
  ('Faris Ahmad Saifuddin', 'Faris.Saifuddin@interport.co.id'),
  ('Farrah Allysha Maharani', 'Farrah.Maharani@interport.co.id'),
  ('Fauzan Aditio', 'Fauzan.Aditio@interport.co.id'),
  ('Fauzi', 'fauzi.f@interport.co.id'),
  ('Febriliawan Dewanti H', 'Febriliawan.Hariyanto@interport.co.id'),
  ('Ferdinand Tarigan', 'ferdinand.tarigan@interport.co.id'),
  ('Ferdinandus Christian M', 'Ferdinandus.Mardiyono@interport.co.id'),
  ('Fitriana', 'Fitriana@interport.co.id'),
  ('Fransiscus Harseno', 'Fransiscus.Harseno@interport.co.id'),
  ('Free Apiantoro', 'free.apiantoro@interport.co.id'),
  ('Gladys Christa Sumuweng', 'Gladys.Sumuweng@interport.co.id'),
  ('Gomfie Tua Hamonangan Sidabutar', 'gomfie.sidabutar@interport.co.id'),
  ('Grace Roben', 'Grace.Roben@interport.co.id'),
  ('Gregorius Nugrohojati Kustadi', 'Gregorius.Kustadi@interport.co.id'),
  ('Griska Devinta Debby', 'Griska.Debby@interport.co.id'),
  ('Gusna Arfian', 'Gusna.Arfian@interport.co.id'),
  ('Gusti Panji Bintang Budiman', 'Gusti.Budiman@interport.co.id'),
  ('Hanif Shafana Nuhi', 'Hanif.Nuhi@interport.co.id'),
  ('Haris Fadlian Noor', 'Haris.Noor@interport.co.id'),
  ('Haryadi', 'Haryadi.H@interport.co.id'),
  ('Hendra Gunawan', 'hendra.gunawan@interport.co.id'),
  ('Hendrik', 'hendrik.h@interport.co.id'),
  ('Hendrik Bagus Wahyudi', 'Hendrik.Wahyudi@interport.co.id'),
  ('Herva Zefanya Sari', 'Herva.Sari@interport.co.id'),
  ('Hilda Hustiniar Thamrin', 'Hilda.Thamrin@interport.co.id'),
  ('Hormonsyah Putra Guci', 'Hormonsyah.Guci@interport.co.id'),
  ('Humaira Khoirunnisa', 'Humaira.Khoirunnisa@interport.co.id'),
  ('Ihsan Adji Pratama', 'ihsan.pratama@interport.co.id'),
  ('Iman Gandi Mihardja', 'iman.mihardja@interport.co.id'),
  ('Indah Hapsari Dewi', 'indah.dewi@interport.co.id'),
  ('Inggita Pramesti', 'Inggita.Pramesti@interport.co.id'),
  ('Intan Rizky Meiwulansari', 'Intan.Meiwulansari@interport.co.id'),
  ('Iqbal Fahmi Faisal', 'Iqbal.Faisal@interport.co.id'),
  ('Ismail', 'Ismail@interport.co.id'),
  ('Ismail', 'Ismail.I@interport.co.id'),
  ('Itjie Tandi Karang', 'Itjie.Tandikarang@interport.co.id'),
  ('Jannata Prijanadi', 'Jannata.Prijanadi@Interport.co.id'),
  ('Jasmine Danella Sihaloho', 'Jasmine.Sihaloho@interport.co.id'),
  ('Jhordya Agustin Hasbullah', 'Jhordya.Hasbullah@interport.co.id'),
  ('Johan Arifin', 'Johan.Arifin@interport.co.id'),
  ('Joko Santoso', 'Joko.Santoso@interport.co.id'),
  ('Kiki Rizki Rahman', 'Kiki.Rahman@interport.co.id'),
  ('Kukuh Henda Tripradana', 'kukuh.tripradana@interport.co.id'),
  ('La Heri Senia', 'La.Senia@interport.co.id'),
  ('Licco Putra Gareynolpratama', 'Licco.Gareynolpratama@interport.co.id'),
  ('Linda Astriyani', 'Linda.Astriyani@interport.co.id'),
  ('M. Fitrah Ramadhan Yusuf', 'M.Yusuf@interport.co.id'),
  ('M. Najih Burhanudin', 'Muhammad.Burhanudin@interport.co.id'),
  ('M. Syahrul Mifta F', 'Syahrul.Mifta@interport.co.id'),
  ('Magfirah', 'magfirah.m@interport.co.id'),
  ('Maria Cloudia Cika Mada', 'Maria.Mada@interport.co.id'),
  ('Mayerina Auliani Rahayu', 'Mayerina.Rahayu@interport.co.id'),
  ('Medina', 'Medina.M@interport.co.id'),
  ('Meiselwon Kholiq', 'Meiselwon.kholiq@interport.co.id'),
  ('Mia Rosmiati M Putri', 'Mia.Putri@interport.co.id'),
  ('Miriana Pradiptari', 'Miriana.Pradiptari@interport.co.id'),
  ('Mitarani Asita', 'Mitarani.Asita@interport.co.id'),
  ('Moh. Fauzi', 'Moh.Fauzi@interport.co.id'),
  ('Moh. Wahdi Wildan Purmadi', 'moh.purmadi@interport.co.id'),
  ('Mohammad Saifur Rahman', 'Mohammad.Rahman@interport.co.id'),
  ('Muhammad Chose', 'muhammad.chose@interport.co.id'),
  ('Muhammad Fadhil Althaf', 'fadhil.althaf@interport.co.id'),
  ('Muhammad Farhan Ichsan Naval', 'Muhammad.Naval@interport.co.id'),
  ('Muhammad Hendrik Saputra', 'Muhammad.Saputra@interport.co.id'),
  ('Muhammad Rizky Julianto', 'muhammad.julianto@interport.co.id'),
  ('Muhammad Rusydani Shubkhi', 'Muhammad.Shubkhi@interport.co.id'),
  ('Muhammad Shofiyuddin', 'Muhammad.Shofiyuddin@interport.co.id'),
  ('Nadia Chita Sandra', 'Nadia.Sandra@interport.co.id'),
  ('Nandang Mulyana', 'Nandang.Mulyana@interport.co.id'),
  ('Nandar Kurniawan', 'nandar.kurniawan@interport.co.id'),
  ('Narendra Riswanto', 'Narendra.Riswanto@interport.co.id'),
  ('Nasimah Fatimah', 'nasimah.fatimah@interport.co.id'),
  ('Nevi Setyasih', 'Nevi.Setyasih@interport.co.id'),
  ('Nindi Distria Rise Meriana', 'Nindi.Meriana@interport.co.id'),
  ('Nisa Angelia', 'Nisa.Angelia-INT@interport.co.id'),
  ('Novandi Nasty Sandya', 'novandi.sandya@interport.co.id'),
  ('Novi Indah Lestari', 'Novi.Lestari@interport.co.id'),
  ('Noviyanti Sari', 'Noviyanti.Sari@interport.co.id'),
  ('Nugroho Hendartono', 'Nugroho.Hendartono@interport.co.id'),
  ('Nur Adnan', 'Nur.Adnan@interport.co.id'),
  ('Nurul Fadhilah', 'Nurul.Fadilah@interport.co.id'),
  ('Oktavia Lija Setyana Situmeang', 'Octavia.Situmeang@interport.co.id'),
  ('Oping Setya Noarista', 'oping.noarista@interport.co.id'),
  ('Pangngo Lyono', 'Pangngolyono@interport.co.id'),
  ('Pawestri Wulan Ramadani', 'Pawestri.Ramadani@interport.co.id'),
  ('Praditya Imandha Pramudji', 'Praditya.Pramudji@interport.co.id'),
  ('Prayogi Akbar Putra', 'Prayogi.akbar@interport.co.id'),
  ('Pujo Dwi Priyatno', 'Pujo.Dwi@interport.co.id'),
  ('Radityo Danisworo', 'Radityo.Danisworo@interport.co.id'),
  ('Rafi Raihan Wahid', 'rafi.wahid@interport.co.id'),
  ('Rafli Ananta Zikri', 'Rafli.Zikri@interport.co.id'),
  ('Rahma Ulfaz Hamima', 'Rahma.Hamima@interport.co.id'),
  ('Raisha Melfani', 'raisha.melfani@interport.co.id'),
  ('Raka Awfa Ghithraf Safari', 'Raka.Safari@interport.co.id'),
  ('Rakhmad Arie Prabowo', 'Rakhmad.Prabowo@interport.co.id'),
  ('Raminda Adiati', 'Raminda.Adiati@interport.co.id'),
  ('Randi Andhika', 'Randi.Andhika@interport.co.id'),
  ('Rasyid Arya Putra', 'Rasyid.Putra-INT@interport.co.id'),
  ('Renata Febry Tj.', 'Renata.Tjanlunggun@interport.co.id'),
  ('Rendy Ramadhan Zein', 'rendy.zein@interport.co.id'),
  ('Rengga Ramadhana Ichwanus S', 'rengga.ichwanus@interport.co.id'),
  ('Restrimaya Susiwi', 'Restrimaya.Susiwi@interport.co.id'),
  ('Reza Dimas Nugroho', 'Reza.Nugroho@interport.co.id'),
  ('Reza Pahlevi Rianka Vatra', 'Reza.Vatra@interport.co.id'),
  ('Riani Abdulsalam', 'Riani.Abdulsalam@interport.co.id'),
  ('Ricky Aprilyanto', 'ricky.aprilyanto@interport.co.id'),
  ('Ricky Guspratama, ST', 'Ricky.Guspratama@interport.co.id'),
  ('Rievan Reisyer', 'rievan.reisyer@interport.co.id'),
  ('Rievandra Devita Novennia', 'Rievandra.Novennia@interport.co.id'),
  ('Rini Yurnalis', 'Rini.Yurnalis@interport.co.id'),
  ('Rion Rori', 'rion.rori@interport.co.id'),
  ('Rizki Amrizal', 'rizki.amrizal@interport.co.id'),
  ('Rizkiakbar Foresandhi', 'Rizkiakbar.Foresandhi@interport.co.id'),
  ('Rochman', 'Rochman@interport.co.id'),
  ('Rosari Silalahi', 'Rosari.Silalahi@interport.co.id'),
  ('Rosmita Nuraini', 'Rosmita.Nuraini@interport.co.id'),
  ('Rossy Gulshan Simanjuntak', 'Rossy.Simanjuntak@interport.co.id'),
  ('Rotua Astrisianna', 'Rotua.Astrisianna@interport.co.id'),
  ('Rubby Purikasanto', 'rubby.purikasanto@interport.co.id'),
  ('Rudi Setiawan', 'Rudi.Setiawan@Interport.co.id'),
  ('Rudy Indrayadi', 'Rudy.Indrayadi@interport.co.id'),
  ('Said Maulana Mahdali', 'said.mahdali@interport.co.id'),
  ('Satwika Indramantanu', 'Satwika.Indramantanu@interport.co.id'),
  ('Selly Meidiansari', 'Selly.Meidiansari@interport.co.id'),
  ('Sesy Widya Pakpahan', 'sesy.pakpahan@interport.co.id'),
  ('Shafira Karamina', 'shafira.karamina@interport.co.id'),
  ('Siti Asylla Mulia', 'siti.mulia@interport.co.id'),
  ('Siti Mutmaina', 'Siti.Mutmaina@interport.co.id'),
  ('Steaven', 'steaven.s@interport.co.id'),
  ('Subakir', 'subakir.s@interport.co.id'),
  ('Sunarto', 'Sunarto@interport.co.id'),
  ('Suryo Adhi Nugroho', 'Suryo.Nugroho@interport.co.id'),
  ('Sustia Agustini', 'Sustia.Agustini@interport.co.id'),
  ('Sutarno', 'Sutarno@interport.co.id'),
  ('Sutrisno Wibowo', 'Sutrisno.Wibowo@interport.co.id'),
  ('Suyanto', 'suyanto.s@interport.co.id'),
  ('Syafruddin', 'syafrudin@interport.co.id'),
  ('Syahid Bil Qisti', 'Syahid.qisti@interport.co.id'),
  ('Tegar Perkasa Darmawan', 'Tegar.Perkasa@interport.co.id'),
  ('Tirsa Awuy', 'Tirsa.Awuy@interport.co.id'),
  ('Tito Alfani', 'Tito.Alfani@interport.co.id'),
  ('Tressya Shafa Amara Ahadi', 'Tressya.Ahadi@interport.co.id'),
  ('Tumbur Parulian Siringoringo', 'tumbur.siringoringo@interport.co.id'),
  ('Vas Artiana', 'Vas.Artiana@interport.co.id'),
  ('Vincensius Septian Ardiarto', 'Vincensius.Ardianto@interport.co.id'),
  ('Vindra Yudha Hendrawan', 'Vindra.Hendrawan@interport.co.id'),
  ('Wahyu Harja Saputra', 'Wahyu.Saputra@interport.co.id'),
  ('Wella Diniati', 'Wella.Diniati@interport.co.id'),
  ('Wien Goerindro', 'Wien.Goerindro@interport.co.id'),
  ('Wilujeng Damayanti', 'Wilujeng.Damayanti@interport.co.id'),
  ('Yohanes K. Gatot Mulyono T', 'Yohanes.Mulyono@interport.co.id'),
  ('Yukki Nugrahawan Hanafi', 'Yukki.Nugrahawan@interport.co.id'),
  ('Yulinar Triana', 'Yulinar.Triana@interport.co.id'),
  ('Yusuf Hasani', 'Yusuf.Hasani@interport.co.id'),
  ('Yusuf Indrawarman', 'Yusuf.Indrawarman@interport.co.id'),
  ('Zahwa Nawang Sinta', 'zahwa.sinta@interport.co.id'),
  ('Zakariya', 'zakariya.z@interport.co.id'),
  ('Zarkasi', 'Zarkasi@interport.co.id'),
  ('Zulfian', 'Zulfian.Z@interport.co.id')
on conflict ((lower(email))) where email is not null do nothing;

-- ---------------------------------------------------------------------------
-- Cari identitas berdasarkan email PENUH (dipakai halaman "Pilih identitas")
-- Karyawan mengetik email kantor Interport lengkap lalu Enter; hanya cocok
-- persis (case-insensitive), tidak menampilkan seluruh daftar karyawan.
-- ---------------------------------------------------------------------------
create or replace function public.find_employee_by_email(p_email text) returns table(id uuid, name text, email text, department text)
language sql stable security definer set search_path = public as $$
  select id, name, email, department from public.profiles
  where active and email is not null and lower(email) = lower(trim(p_email))
  limit 1;
$$;

-- Fungsi lama yang mengekspos SELURUH daftar karyawan (nama+email) ke publik
-- sudah tidak dipakai frontend -- dihapus supaya datanya tidak bisa ditarik
-- borongan lewat API, hanya bisa dicari satu-satu pakai email penuh.
drop function if exists public.employee_directory();
